name: Build Packages

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-packages:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        package: [mosaic]
    defaults:
      run:
        working-directory: packages/${{ matrix.package }}
    env:
      ROLLUP_SKIP_NATIVE: 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Use Node.js 20.x
        uses: actions/setup-node@v6
        with:
          node-version: '20.x'

      - name: Install dependencies (npm install)
        run: npm install --no-audit --no-fund

      - name: Build frontend (npm run build)
        run: npm run build
