name: Code Quality

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    env:
      COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.ACCESS_TOKEN }}"} }'
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Cache Dependencies PHP
        id: php-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: dependencies-php-composer-${{ hashFiles('composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: curl, dom, fileinfo, intl, json, libxml, mbstring, simplexml, zip
          tools: composer:v2

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --ansi --optimize-autoloader

      - name: Run Pint (Code Style)
        run: composer lint

      - name: Run PHPStan (Static Analysis)
        run: composer analyze

      - name: Run Rector (Code Refactoring)
        run: composer rector
