name: 'Prettier Code Styling'

on:
  pull_request:
    paths:
      - 'packages/**/*.{css,js,yml,blade.php}'

permissions:
  contents: write

jobs:
  prettier:
    runs-on: ubuntu-latest
    env:
      COMPOSER_AUTH: |
        {
          "github-oauth": {
            "github.com": "${{ secrets.ACCESS_TOKEN }}"
          }
        }
    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Configure npm caching
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Prettify code
        run: npx prettier --write 'packages/**/*.{css,js,yml,blade.php}' '!packages/**/node_modules/**'

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Prettier code styling fixes 🎨
