name: monorepo-split

on:
  push:
    tags: '*'

jobs:
  split-monorepo:
    runs-on: ubuntu-latest
    env:
      COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.ACCESS_TOKEN }}"} }'
    strategy:
      fail-fast: false
      matrix:
        package:
          - address
          - blog
          - hero
          - layout
    steps:
      - uses: actions/checkout@v6
      - id: previous-tag
        uses: 'WyriHaximus/github-action-get-previous-tag@master'
      - name: Monorepo Split of ${{ matrix.package }}
        uses: danharrin/monorepo-split-github-action@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: 'packages/${{ matrix.package }}'
          repository_organization: 'capell-app'
          repository_name: '${{ matrix.package }}'
          branch: '4.x'
          tag: ${{ steps.previous-tag.outputs.tag }}
          user_name: 'capell-app'
          user_email: 'appcapello@gmail.com'
